[build]
  command = "npm install"
  publish = "."

[[redirects]]
  from = "/opportunities"
  to = "/opportunities.html"
  status = 200

[[redirects]]
  from = "/trips"
  to = "/trips.html"
  status = 200

[[redirects]]
  from = "/trips/thailand"
  to = "/trip-thailand.html"
  status = 200

[[redirects]]
  from = "/trips/south-africa"
  to = "/trip-south-africa.html"
  status = 200

[[redirects]]
  from = "/trips/bali"
  to = "/trip-bali.html"
  status = 200

[[redirects]]
  from = "/trips/vietnam"
  to = "/trip-vietnam.html"
  status = 200

[[redirects]]
  from = "/destinations"
  to = "/destinations.html"
  status = 200

[[redirects]]
  from = "/destination/bali"
  to = "/destination-bali.html"
  status = 200

[[redirects]]
  from = "/destination/thailand"
  to = "/destination-thailand.html"
  status = 200

[[redirects]]
  from = "/destination/vietnam"
  to = "/destination-vietnam.html"
  status = 200

[[redirects]]
  from = "/destination/south-africa"
  to = "/destination-south-africa.html"
  status = 200

[[redirects]]
  from = "/travel"
  to = "/opportunities.html"
  status = 301

[[redirects]]
  from = "/recruitment"
  to = "/opportunities.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
